const VARIABLE = import.meta.env;

const SERVER_STATUS = VARIABLE.VITE_SERVER_STATUS;
const API_URL = VARIABLE.VITE_API_URL;
const CLOUDINARY_CLOUD_NAME = VARIABLE.VITE_CLOUDINARY_CLOUD_NAME;
export { API_URL, SERVER_STATUS, CLOUDINARY_CLOUD_NAME };
